---

services:
  alexandria:
    build: .
    image: alexandria
    restart: always
    ports:
      - 8080:8080
    environment:
      ALLOWED_HOSTS: "*"
      SECRET_KEY: very-non-secure-django-secret-key
      DJANGO_SETTINGS_MODULE: alexandria.settings.production
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
    healthcheck:
      test: ["CMD-SHELL", "curl", "-sSL", "http://localhost:8080/_health/"]
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      retries: 3
      start_period: 15s
      timeout: 10s
