---

services:
  alexandria:
    build: .
    image: alexandria
    restart: always
    ports:
      - 8080:8080
    environment:
      ALLOWED_HOSTS: "*"
      SECRET_KEY: "very-non-secure-django-secret-key"
      DJANGO_SETTINGS_MODULE: "alexandria.settings"

  db:
    image: postgres:alpine
    ports:
      5432:5432
